# Project information
site_name: REPO_NAME_OR_SITE_NAME
site_url: https://kenan-blasius.github.io/github-pages-learning/
site_author: Author
site_description: >-
  DESCRIPTION

# define the tree structure of the site
nav:
  - Home: index.md
  - Simple File: test-1.md
  - Markdown Demo: markdown_demo.md
  - Simple Folder:
    - File in a folder: folder-test/test-1 copy.md
    - File in a folder 2: folder-test/test-1 copy 2.md

# Copyright
copyright: Copyright &copy; copyright example

# Repository
repo_name: REPO_NAME
repo_url: https://REPO_URL

# Configuration
theme:
  name: material
  # Static files
  static_templates:
    - 404.html
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  language: fr
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: indigo
      accent: indigo
  # icon du site
  favicon: assets/favicon
  # icon du header
  icon:
    repo: fontawesome/brands/github
    logo: logo

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/

extra_css:
  - css/example.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables

plugins:
  - search
